
'use client';

import { motion } from 'framer-motion';
import { UserPlus, Target, BarChartBig, Brain } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

const steps = [
  {
    icon: <UserPlus className="h-8 w-8 text-primary" />,
    title: "1. Choose Your Role",
    description: "Select from over 30 professional roles like 'AI Engineer' or 'Frontend Developer'."
  },
  {
    icon: <Target className="h-8 w-8 text-primary" />,
    title: "2. Take the Dynamic Test",
    description: "Engage with a unique assessment generated by AI, featuring MCQs, coding challenges, and more."
  },
  {
    icon: <BarChartBig className="h-8 w-8 text-primary" />,
    title: "3. Get Instant Analytics",
    description: "Receive a detailed breakdown of your skills, strengths, and weaknesses on your dashboard."
  },
  {
    icon: <Brain className="h-8 w-8 text-primary" />,
    title: "4. Follow Your AI Path",
    description: "Use your personalized, AI-generated learning path to improve and master new skills."
  }
];

export function HowItWorks() {
  const containerVariants = {
    hidden: {},
    visible: {
      transition: {
        staggerChildren: 0.2,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 50 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.5,
        ease: 'easeOut'
      }
    },
  };

  return (
    <section id="how-it-works" className="py-16 sm:py-24">
      <div className="container mx-auto px-4 md:px-6">
        <div className="text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">A Clear Path to Mastery</h2>
          <p className="mt-4 max-w-xl mx-auto text-muted-foreground md:text-xl">
            Your journey from aspiration to expertise in four simple steps.
          </p>
        </div>
        <motion.div 
          className="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6"
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.1 }}
        >
          {steps.map((step, index) => (
            <motion.div key={index} variants={itemVariants} className="h-full">
              <Card className="h-full text-center bg-card/60 backdrop-blur-sm border-border/20 shadow-lg transition-all duration-300 hover:border-primary/60 hover:shadow-primary/10 hover:-translate-y-1">
                <CardHeader>
                    <div className="mx-auto flex items-center justify-center bg-primary/10 p-4 rounded-full border w-fit mb-4">
                        {step.icon}
                    </div>
                    <CardTitle>{step.title}</CardTitle>
                </CardHeader>
                <CardContent>
                    <CardDescription>{step.description}</CardDescription>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
